workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - deploy

build_linux:
  stage: build
  tags:
    - linux
  variables:
    GIT_STRATEGY: fetch
  script:
    - dotnet publish -c Release -r linux-x64 --output linux --no-self-contained 
    - rm linux/libif_cfs.dll
  
  artifacts:
    name: db-bridge.linux
    expire_in: 1 day
    paths:
      - linux/
        
build_windows:
  stage: build
  tags:
    - linux
  variables:
    GIT_STRATEGY: fetch
  script:
    - dotnet publish -c Release -r win-x64 --output windows --no-self-contained
    - rm windows/libif_cfs.so
  
  artifacts:
    name: db-bridge.windows
    expire_in: 1 day
    paths:
      - windows/

deploy_linux:
  stage: deploy
  tags:
    - win10
  variables:
    ARTIFACT_DIR: "C:\\Artifacts\\Iface.Oik.DB-bridge\\Linux"

  dependencies:
    - build_linux
  script:
    - if (Test-Path $ARTIFACT_DIR ) { Remove-Item $ARTIFACT_DIR -Recurse -Force }
    - New-Item -ItemType "directory" -Path $ARTIFACT_DIR -Force
    - Copy-Item linux/* $ARTIFACT_DIR

deploy_windows:
  stage: deploy
  tags:
    - win10
  variables:
    ARTIFACT_DIR: "C:\\Artifacts\\Iface.Oik.DB-bridge\\Windows"

  dependencies:
    - build_windows
  script:
    - if (Test-Path $ARTIFACT_DIR ) { Remove-Item $ARTIFACT_DIR -Recurse -Force }
    - New-Item -ItemType "directory" -Path $ARTIFACT_DIR -Force
    - Copy-Item linux/* $ARTIFACT_DIR
