<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Iface.Oik.DB_bridge</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Iface.Oik.Tm">
      <HintPath>..\Iface.Oik.Tm\src\Iface.Oik.Tm\bin\Debug\netstandard2.0\Iface.Oik.Tm.dll</HintPath>
    </Reference>
    <Reference Include="Iface.Oik.Tm.Native">
      <HintPath>..\Iface.Oik.Tm\src\Iface.Oik.Tm\bin\Debug\netstandard2.0\Iface.Oik.Tm.Native.dll</HintPath>
    </Reference>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.2" />
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.2" />
	  <PackageReference Include="MySql.Data" Version="8.0.31" />
	  <PackageReference Include="Npgsql" Version="7.0.1" />
	  <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
	  <PackageReference Include="System.Text.Encoding.CodePages" Version="4.7.0" />
  </ItemGroup>
</Project>
